"""Embeds the profession and elite specialization icons into the addon.

Icons come from the official GW2 API (render.guildwars2.com): /v2/professions "icon_big" saved as
assets/icons/prof_<profession id>.png, /v2/specializations "profession_icon_big" of elite specializations as
assets/icons/spec_<specialization id>.png. They are 64x64 grey images, tinted with the profession colour when drawn.

Run: python tools/gen_icons.py  (writes src/IconData.inc)
"""
import json
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
icons = root / "assets" / "icons"
specs = {s["id"]: s for s in json.loads((root / "reference" / "specializations.json").read_text(encoding="utf-8"))}
codes = {p["id"]: p["code"] for p in json.loads((root / "reference" / "professions.json").read_text(encoding="utf-8"))}

entries = []  # (profession id, specialization id or 0, file)
for path in sorted(icons.glob("prof_*.png"), key=lambda p: int(p.stem[5:])):
    entries.append((int(path.stem[5:]), 0, path))
for path in sorted(icons.glob("spec_*.png"), key=lambda p: int(p.stem[5:])):
    spec = specs[int(path.stem[5:])]
    entries.append((codes[spec["profession"]], spec["id"], path))

lines = ["// Generated by tools/gen_icons.py from assets/icons. Do not edit.", ""]
for profession, spec, path in entries:
    data = path.read_bytes()
    body = ",".join(str(b) for b in data)
    lines.append(f"static const unsigned char kIcon_{path.stem}[] = {{{body}}};")
lines.append("")
lines.append("static const IconBlob kIconBlobs[] = {")
for profession, spec, path in entries:
    lines.append(f"\t{{ {profession}, {spec}, kIcon_{path.stem}, sizeof(kIcon_{path.stem}) }},")
lines.append("};")
(root / "src" / "IconData.inc").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {len(entries)} icons")
